using System.Globalization;
using System.IO;
using System.Text;
using System.Windows.Media;
using System.Windows.Media.Imaging;

namespace Lasero.MotionTool;

/// <summary>
/// Turns the raster brand wordmark into clean vector contours (marching squares on a 4x bilinear
/// upsample of two ink fields, then Douglas-Peucker). The raster stays the brand source of truth;
/// the output, Controls/Motion/WordmarkData.cs, is what the animation draws. Deterministic: the
/// same PNG always yields the same file.
/// </summary>
internal static class WordmarkTracer
{
    private const int Up = 4;
    private const double SimplifyTolerance = 0.07; // source pixels

    private readonly record struct Pt(double X, double Y);
    private readonly record struct Rect(double X0, double Y0, double X1, double Y1);

    public static int Run(Options o)
    {
        var png = o.Require("png");
        var outFile = o.Require("out");
        var decoder = BitmapDecoder.Create(new Uri(Path.GetFullPath(png)), BitmapCreateOptions.None, BitmapCacheOption.OnLoad);
        var src = new FormatConvertedBitmap(decoder.Frames[0], PixelFormats.Bgra32, null, 0);
        int w = src.PixelWidth, h = src.PixelHeight;
        var px = new byte[w * h * 4];
        src.CopyPixels(px, w * 4, 0);

        var dark = new double[w * h];
        var red = new double[w * h];
        for (var i = 0; i < w * h; i++)
        {
            double b = px[i * 4], g = px[i * 4 + 1], r = px[i * 4 + 2], a = px[i * 4 + 3] / 255.0;
            // composite over white so a transparent PNG and an opaque one trace the same
            r = r * a + 255 * (1 - a); g = g * a + 255 * (1 - a); b = b * a + 255 * (1 - a);
            dark[i] = 1 - Math.Max(r, Math.Max(g, b)) / 255.0;
            red[i] = Math.Clamp((r - Math.Max(g, b)) / 255.0, 0, 1);
        }

        var darkLoops = Contours(dark, w, h);
        var redLoops = Contours(red, w, h);
        Console.WriteLine($"graphite loops: {darkLoops.Count}, red loops: {redLoops.Count}");

        var infos = darkLoops.Select(l => (Pts: l, Box: Box(l), Area: Math.Abs(Area(l)))).ToList();
        foreach (var i in infos)
            Console.WriteLine($"  dark loop pts={i.Pts.Count} box=({i.Box.X0:F1},{i.Box.Y0:F1})-({i.Box.X1:F1},{i.Box.Y1:F1}) area={i.Area:F0}");
        foreach (var l in redLoops)
        {
            var b = Box(l);
            Console.WriteLine($"  red loop pts={l.Count} box=({b.X0:F1},{b.Y0:F1})-({b.X1:F1},{b.Y1:F1})");
        }

        // outer = not contained in a bigger loop; holes are attached to the outer that contains them
        var outers = infos.Where(a => !infos.Any(b => b.Area > a.Area && Inside(b.Box, a.Box))).OrderBy(a => a.Box.X0).ToList();
        var holes = infos.Except(outers).ToList();
        var names = new[] { "L", "A", "S", "E", "R", "O" };
        var headStart = names.Length;
        if (outers.Count <= headStart) throw new InvalidOperationException("Unexpected trace: only " + outers.Count + " outer loops");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by tools/motion/Lasero.MotionTool (trace-wordmark) from Assets/LaseroWordmark.png.");
        sb.AppendLine("// Do not edit by hand; run tools/motion/Trace-Wordmark.ps1 to regenerate.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("namespace Lasero.App.Controls.Motion;");
        sb.AppendLine();
        sb.AppendLine("internal static class WordmarkData");
        sb.AppendLine("{");
        sb.AppendLine($"    public const double Width = {w.ToString(CultureInfo.InvariantCulture)};");
        sb.AppendLine($"    public const double Height = {h.ToString(CultureInfo.InvariantCulture)};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Graphite outlines in reading order: L A S E R O, then the laser head pieces.</summary>");
        sb.AppendLine("    public static readonly WordmarkGroup[] Groups =");
        sb.AppendLine("    {");

        for (var gi = 0; gi < headStart; gi++)
        {
            var own = outers[gi];
            EmitGroup(sb, names[gi], new[] { own.Pts }.Concat(holes.Where(hh => Inside(own.Box, hh.Box)).Select(x => x.Pts)));
        }
        var headOuters = outers.Skip(headStart).ToList();
        EmitGroup(sb, "Head", headOuters.Select(x => x.Pts)
            .Concat(holes.Where(hh => headOuters.Any(ho => Inside(ho.Box, hh.Box))).Select(x => x.Pts)));
        sb.AppendLine("    };");
        sb.AppendLine();

        if (redLoops.Count == 0) throw new InvalidOperationException("No red beam found");
        var rb = Box(redLoops.OrderByDescending(l => Math.Abs(Area(l))).First());
        var dotR = (rb.X1 - rb.X0) / 2;
        var cx = (rb.X0 + rb.X1) / 2;
        var dotCy = rb.Y1 - dotR;
        // beam width: red coverage summed across a row mid-way down the beam
        var midY = (int)((rb.Y0 + dotCy) / 2);
        double beamW = 0;
        for (var x = (int)rb.X0 - 2; x <= (int)rb.X1 + 2; x++)
            if (x >= 0 && x < w) beamW += red[midY * w + x];
        sb.AppendLine("    // Measured from the red ink of the raster wordmark.");
        sb.AppendLine($"    public const double BeamX = {F(cx)};");
        sb.AppendLine($"    public const double BeamTop = {F(rb.Y0)};");
        sb.AppendLine($"    public const double BeamWidth = {F(beamW)};");
        sb.AppendLine($"    public const double DotCenterY = {F(dotCy)};");
        sb.AppendLine($"    public const double DotRadius = {F(dotR)};");
        sb.AppendLine("}");
        File.WriteAllText(outFile, sb.ToString(), new UTF8Encoding(false));
        Console.WriteLine("Wrote " + outFile);
        return 0;
    }

    private static string F(double v) => v.ToString("0.##", CultureInfo.InvariantCulture);

    private static void EmitGroup(StringBuilder sb, string name, IEnumerable<List<Pt>> loops)
    {
        sb.AppendLine($"        new(\"{name}\", new[]");
        sb.AppendLine("        {");
        foreach (var l in loops)
        {
            sb.Append("            new double[] { ");
            sb.Append(string.Join(", ", l.Select(p => F(p.X) + ", " + F(p.Y))));
            sb.AppendLine(" },");
        }
        sb.AppendLine("        }),");
    }

    private static bool Inside(Rect outer, Rect inner) =>
        inner.X0 >= outer.X0 - 0.5 && inner.X1 <= outer.X1 + 0.5 && inner.Y0 >= outer.Y0 - 0.5 && inner.Y1 <= outer.Y1 + 0.5;

    private static Rect Box(List<Pt> l) => new(l.Min(p => p.X), l.Min(p => p.Y), l.Max(p => p.X), l.Max(p => p.Y));

    private static double Area(List<Pt> l)
    {
        double a = 0;
        for (var i = 0; i < l.Count; i++) { var p = l[i]; var q = l[(i + 1) % l.Count]; a += p.X * q.Y - q.X * p.Y; }
        return a / 2;
    }

    // ---- marching squares -----------------------------------------------------------------------

    private static double Sample(double[] f, int w, int h, double x, double y)
    {
        var fx = Math.Clamp(x - 0.5, 0, w - 1.0001); var fy = Math.Clamp(y - 0.5, 0, h - 1.0001);
        int ix = (int)fx, iy = (int)fy; var tx = fx - ix; var ty = fy - iy;
        var a = f[iy * w + ix]; var b = f[iy * w + ix + 1]; var c = f[(iy + 1) * w + ix]; var d = f[(iy + 1) * w + ix + 1];
        return (a * (1 - tx) + b * tx) * (1 - ty) + (c * (1 - tx) + d * tx) * ty;
    }

    private static List<List<Pt>> Contours(double[] f, int w, int h)
    {
        int gw = w * Up, gh = h * Up;
        // padded grid so shapes touching the image edge still close
        var stride = gw + 2;
        var grid = new double[stride * (gh + 2)];
        for (var j = 0; j < gh; j++)
            for (var i = 0; i < gw; i++)
                grid[(j + 1) * stride + i + 1] = Sample(f, w, h, (i + 0.5) / Up, (j + 0.5) / Up);

        double G(int i, int j) => grid[(j + 1) * stride + i + 1];
        const double T = 0.5;
        var segments = new List<(Pt a, Pt b)>();

        for (var j = -1; j < gh; j++)
            for (var i = -1; i < gw; i++)
            {
                double v0 = G(i, j), v1 = G(i + 1, j), v2 = G(i + 1, j + 1), v3 = G(i, j + 1);
                var idx = (v0 >= T ? 1 : 0) | (v1 >= T ? 2 : 0) | (v2 >= T ? 4 : 0) | (v3 >= T ? 8 : 0);
                if (idx == 0 || idx == 15) continue;
                var ci = i; var cj = j;
                Pt E(int e) => e switch
                {
                    0 => new Pt(ci + Lerp(v0, v1), cj),
                    1 => new Pt(ci + 1, cj + Lerp(v1, v2)),
                    2 => new Pt(ci + Lerp(v3, v2), cj + 1),
                    _ => new Pt(ci, cj + Lerp(v0, v3)),
                };
                void Add(int e1, int e2) => segments.Add((E(e1), E(e2)));
                switch (idx)
                {
                    case 1: case 14: Add(3, 0); break;
                    case 2: case 13: Add(0, 1); break;
                    case 3: case 12: Add(3, 1); break;
                    case 4: case 11: Add(1, 2); break;
                    case 6: case 9: Add(0, 2); break;
                    case 7: case 8: Add(3, 2); break;
                    case 5: case 10:
                        var center = (v0 + v1 + v2 + v3) / 4;
                        if ((idx == 5) == (center >= T)) { Add(3, 0); Add(1, 2); } else { Add(0, 1); Add(3, 2); }
                        break;
                }
            }

        static double Lerp(double a, double b) => (T - a) / (b - a);
        static long Key(Pt p) => ((long)Math.Round(p.X * 64) << 32) ^ (long)Math.Round(p.Y * 64);

        var byEnd = new Dictionary<long, List<int>>();
        for (var s = 0; s < segments.Count; s++)
            foreach (var p in new[] { segments[s].a, segments[s].b })
            {
                var k = Key(p);
                if (!byEnd.TryGetValue(k, out var l)) byEnd[k] = l = new List<int>();
                l.Add(s);
            }

        var used = new bool[segments.Count];
        var loops = new List<List<Pt>>();
        for (var s = 0; s < segments.Count; s++)
        {
            if (used[s]) continue;
            used[s] = true;
            var pts = new List<Pt> { segments[s].a, segments[s].b };
            while (true)
            {
                var tail = pts[^1];
                var next = byEnd[Key(tail)].FirstOrDefault(n => !used[n], -1);
                if (next < 0) break;
                used[next] = true;
                var sg = segments[next];
                pts.Add(Key(sg.a) == Key(tail) ? sg.b : sg.a);
            }
            if (pts.Count < 12) continue;
            var conv = pts.Select(p => new Pt((p.X + 0.5) / Up, (p.Y + 0.5) / Up)).ToList();
            if (Math.Abs(Area(conv)) < 4) continue; // specks
            loops.Add(Simplify(conv));
        }
        return loops;
    }

    /// <summary>Closed-loop Douglas-Peucker: split at the two most distant points, simplify both halves.</summary>
    private static List<Pt> Simplify(List<Pt> loop)
    {
        if (loop.Count > 1 && Dist(loop[0], loop[^1]) < 1e-6) loop = loop.Take(loop.Count - 1).ToList();
        var a = 0; var b = 0; double best = -1;
        for (var i = 0; i < loop.Count; i++) { var d = Dist(loop[0], loop[i]); if (d > best) { best = d; a = i; } }
        best = -1;
        for (var i = 0; i < loop.Count; i++) { var d = Dist(loop[a], loop[i]); if (d > best) { best = d; b = i; } }
        if (a > b) (a, b) = (b, a);
        var first = loop.GetRange(a, b - a + 1);
        var second = loop.GetRange(b, loop.Count - b).Concat(loop.GetRange(0, a + 1)).ToList();
        var r = DouglasPeucker(first);
        r.RemoveAt(r.Count - 1);
        r.AddRange(DouglasPeucker(second));
        r.RemoveAt(r.Count - 1);
        return r;
    }

    private static List<Pt> DouglasPeucker(List<Pt> pts)
    {
        if (pts.Count < 3) return pts.ToList();
        var keep = new bool[pts.Count]; keep[0] = keep[^1] = true;
        var stack = new Stack<(int, int)>(); stack.Push((0, pts.Count - 1));
        while (stack.Count > 0)
        {
            var (s, e) = stack.Pop();
            double max = 0; var idx = -1;
            for (var i = s + 1; i < e; i++)
            {
                var d = PointLine(pts[i], pts[s], pts[e]);
                if (d > max) { max = d; idx = i; }
            }
            if (idx >= 0 && max > ToleranceFor(pts[s], pts[e])) { keep[idx] = true; stack.Push((s, idx)); stack.Push((idx, e)); }
        }
        return pts.Where((_, i) => keep[i]).ToList();
    }

    /// <summary>Long chords may deviate more: the AA staircase on a straight diagonal (the A) is about 0.25 px,
    /// while a curve of radius ~45 px already exceeds that over a 20 px chord, so curves keep their detail.</summary>
    private static double ToleranceFor(Pt a, Pt b) => Dist(a, b) >= 20 ? 0.3 : SimplifyTolerance;

    private static double Dist(Pt a, Pt b) => Math.Sqrt((a.X - b.X) * (a.X - b.X) + (a.Y - b.Y) * (a.Y - b.Y));

    private static double PointLine(Pt p, Pt a, Pt b)
    {
        double dx = b.X - a.X, dy = b.Y - a.Y; var len = Math.Sqrt(dx * dx + dy * dy);
        if (len < 1e-9) return Dist(p, a);
        return Math.Abs(dy * p.X - dx * p.Y + b.X * a.Y - b.Y * a.X) / len;
    }
}
